"""Advanced workflow features, kanban, time tracking, knowledge hub."""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20240306_advanced_features"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - edited ###
    op.create_table(
        "task_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("default_priority", sa.String(length=20), nullable=False),
        sa.Column("default_status", sa.String(length=20), nullable=False),
        sa.Column("default_size_points", sa.Integer(), nullable=False),
        sa.Column("default_recurrence_interval_days", sa.Integer(), nullable=True),
        sa.Column("default_requires_approval", sa.Boolean(), nullable=False),
        sa.Column("default_checklist", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_templates_name"), "task_templates", ["name"], unique=True)

    with op.batch_alter_table("tasks") as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(length=20), nullable=False, server_default="backlog"))
        batch_op.add_column(sa.Column("priority", sa.String(length=20), nullable=False, server_default="medium"))
        batch_op.add_column(sa.Column("due_date", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("started_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("completed_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("size_points", sa.Integer(), nullable=False, server_default="1"))
        batch_op.add_column(sa.Column("recurrence_interval_days", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("recurrence_end_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("requires_approval", sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column("approved_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("approved_by", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("blocked_reason", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("blocked_started_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("blocked_minutes_total", sa.Integer(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column("kanban_order", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("template_id", sa.Integer(), nullable=True))
        batch_op.create_index("ix_tasks_status", ["status"])
        batch_op.create_index("ix_tasks_priority", ["priority"])
        batch_op.create_index("ix_tasks_due_date", ["due_date"])
        batch_op.create_index("ix_tasks_started_at", ["started_at"])
        batch_op.create_index("ix_tasks_completed_at", ["completed_at"])
        batch_op.create_foreign_key("fk_tasks_template_id", "task_templates", ["template_id"], ["id"])
        batch_op.create_foreign_key("fk_tasks_approved_by", "users", ["approved_by"], ["id"])

    op.create_table(
        "task_dependencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("depends_on_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["depends_on_id"], ["tasks.id"]),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "depends_on_id", name="uq_task_dep"),
    )
    op.create_index(op.f("ix_task_dependencies_task_id"), "task_dependencies", ["task_id"], unique=False)
    op.create_index(op.f("ix_task_dependencies_depends_on_id"), "task_dependencies", ["depends_on_id"], unique=False)

    op.create_table(
        "time_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_time_entries_task_id"), "time_entries", ["task_id"], unique=False)
    op.create_index(op.f("ix_time_entries_user_id"), "time_entries", ["user_id"], unique=False)

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=120), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_task_id"), "audit_logs", ["task_id"], unique=False)

    op.create_table(
        "task_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_notes_task_id"), "task_notes", ["task_id"], unique=False)
    op.create_index(op.f("ix_task_notes_created_by"), "task_notes", ["created_by"], unique=False)

    op.create_table(
        "task_attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"]),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_attachments_task_id"), "task_attachments", ["task_id"], unique=False)
    op.create_index(op.f("ix_task_attachments_created_by"), "task_attachments", ["created_by"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - edited ###
    op.drop_index(op.f("ix_task_attachments_created_by"), table_name="task_attachments")
    op.drop_index(op.f("ix_task_attachments_task_id"), table_name="task_attachments")
    op.drop_table("task_attachments")

    op.drop_index(op.f("ix_task_notes_created_by"), table_name="task_notes")
    op.drop_index(op.f("ix_task_notes_task_id"), table_name="task_notes")
    op.drop_table("task_notes")

    op.drop_index(op.f("ix_audit_logs_task_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_table("audit_logs")

    op.drop_index(op.f("ix_time_entries_user_id"), table_name="time_entries")
    op.drop_index(op.f("ix_time_entries_task_id"), table_name="time_entries")
    op.drop_table("time_entries")

    op.drop_index(op.f("ix_task_dependencies_depends_on_id"), table_name="task_dependencies")
    op.drop_index(op.f("ix_task_dependencies_task_id"), table_name="task_dependencies")
    op.drop_table("task_dependencies")

    op.drop_index(op.f("ix_task_templates_name"), table_name="task_templates")
    op.drop_table("task_templates")

    with op.batch_alter_table("tasks") as batch_op:
        batch_op.drop_constraint("fk_tasks_approved_by", type_="foreignkey")
        batch_op.drop_constraint("fk_tasks_template_id", type_="foreignkey")
        batch_op.drop_column("blocked_reason")
        batch_op.drop_index("ix_tasks_completed_at")
        batch_op.drop_index("ix_tasks_started_at")
        batch_op.drop_index("ix_tasks_due_date")
        batch_op.drop_index("ix_tasks_priority")
        batch_op.drop_index("ix_tasks_status")
        batch_op.drop_column("template_id")
        batch_op.drop_column("kanban_order")
        batch_op.drop_column("blocked_minutes_total")
        batch_op.drop_column("blocked_started_at")
        batch_op.drop_column("approved_by")
        batch_op.drop_column("approved_at")
        batch_op.drop_column("requires_approval")
        batch_op.drop_column("recurrence_end_date")
        batch_op.drop_column("recurrence_interval_days")
        batch_op.drop_column("size_points")
        batch_op.drop_column("completed_at")
        batch_op.drop_column("started_at")
        batch_op.drop_column("due_date")
        batch_op.drop_column("priority")
        batch_op.drop_column("status")
    # ### end Alembic commands ###
